name: Publish Java Package

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # Permite lanzar el workflow manualmente

jobs:
  build:

    runs-on: ubuntu-latest

    # üîê Permisos para leer y publicar paquetes
    permissions:
      contents: read
      packages: write

    steps:
      # 1Ô∏è‚É£ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3Ô∏è‚É£ Configurar Gradle cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 4Ô∏è‚É£ Asegurar permisos de ejecuci√≥n para el wrapper
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GH_PACKAGES_TOKEN: ${{ secrets.TOKEN }}

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GH_PACKAGES_TOKEN: ${{ secrets.TOKEN }}

